---
title: Anomaly Detection
author: |
  | [Frank Jung](https://www.linkedin.com/in/frankjung/)
  | [The Marlo Group](https://www.marlo.com.au)
  | frank.jung@marlo.com.au
abstract: |
  Anomalies are patterns in data that do not conform to a well-defined notion of
  normal behaviour. There are many different algorithms for anomaly detection
  spanning different categories [@ChandolaBK2009]. In a recent article
  [@Niculaescu2018] the author used a CUSUM algorithm to detect anomalies.
  However, the details of how this was performed was scant. Consequently, we
  decided to replicate the results here. This was done to a gain an
  understanding of the methods used and how parameters are chosen and how to
  interpret the results.
bibliography: anomalies.bib
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/association-for-computing-machinery.csl
header-includes:
  - \usepackage{hyperref}
  - \twocolumn
output: rticles::acm_article
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE, cache.path = "cache/")
knitr::opts_chunk$set(fig.width = 10, fig.height = 7, fig.path = "figure/")

require(ggplot2)
```


# Introduction

Anomalies are patterns in data that do not conform to a well-defined notion of
normal behaviour. There are many different algorithms for anomaly detection
spanning different categories [@ChandolaBK2009]. In a recent article
[@Niculaescu2018] the author used a CUSUM algorithm to detect anomalies.
However, the details of how this was performed was scant. Consequently, we
decided to replicate the results here. This was done to a gain an understanding
of the methods used and how the algorithm parameters are chosen.

_Can the choice of parameters be automated?_


# Test Overview

The data provided in [@Niculaescu2018] was insufficient for testing as it
contained too few anomalies and was a limited sample. Instead, we will simulate
a larger sample with known anomalies randomly included. This will help to
evaluate the accuracy of anomaly detection algorithm when split into training
and validation sets.


# Method

_Detailed description of the test method._


# Overview of Anomaly Detection Algorithm

The [CUSUM](https://en.wikipedia.org/wiki/CUSUM) algorithm is used to test for
anomalies. This requires two parameters: *threshold* and *drift*. But, how do
you choose values for these parameters? [@Gustafsson2000] provides this recipe:

* Start with a very large *threshold*.
* Choose *drift* to one half of the expected change, or adjust drift such that `g = 0` more than 50% of the time.
* Then set the *threshold* so the required number of false alarms (this can be done automatically) or delay for detection is obtained.
* If faster detection is sought, try to decrease *drift*.
* If fewer false alarms are wanted, try to increase *drift*.
* If there is a subset of the change times that does not make sense, try to increase *drift*.

Here we are using
[cusum](https://www.rdocumentation.org/packages/qcc/versions/2.6/topics/cusum)
from the [Quality Control Charts (qcc)
package](https://www.rdocumentation.org/packages/qcc/).


# Tests

_Use sampling process as described above._


# Evaluation

_Use ROC to evaluate._
See also [@Eskin2000].


# Further Work

Here we have replicated the results from [@Niculaescu2018].  This used the CUSUM
algorithm. However, there are numerous other algorithms worth
investigating[@ChandolaBK2009]. One that is designed for time series data is
"Seasonal Hybrid ESD" [@HochenbaumVK2017] from Twitter. This is available as an
open source package,
[AnomalyDetection](https://github.com/twitter/AnomalyDetection). Another that
has proven effective[@He2016] is the unsupervised Invariants Minig algorithm.


# Resources

_Convert to BibTeX references:_

* [AnomalyDetection (GitHub)](https://github.com/twitter/AnomalyDetection)
* [Anomaly Detection in R](https://www.r-bloggers.com/anomaly-detection-in-r-2/)
* [Introducing Practical and Robust Anomaly detection in a Time Series](https://blog.twitter.com/engineering/en_us/a/2015/introducing-practical-and-robust-anomaly-detection-in-a-time-series.html)


# References

